### PR TITLE
feat: Adding LDAP into rules.tf

### PR DESCRIPTION
**Pull request by lazzurs**
Adding LDAP along side LDAPS as LDAP without encryption is still used in places.

Given the rules.tf has both HTTP and HTTPS this appears to be a valid addition.

## Description
Adding TCP 389 LDAP to rules.tf

## Motivation and Context
Adding the default LDAP port to the rules.

## Breaking Changes
No breaking changes.

## How Has This Been Tested?
No tests have been run of this change.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Thank you!

[v3.17.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v3.17.0) has been just released.

**Comment by Porkepix** [comment]
@lazzurs @antonbabenko  It seems https://github.com/terraform-aws-modules/terraform-aws-security-group/commit/0c0572f1811abe554994f43406145ba14ab80aed#diff-dfd5848fa77a04d0343891fe859286cc210473d10f0e62c7f99f0d5ecf1a9927 reverted what was done in https://github.com/terraform-aws-modules/terraform-aws-security-group/pull/184 allowing to use provider v3 reverting to a state where provider is locked to version 2 only.
Is there any reason for this?

**Comment by antonbabenko** [comment]
@Porkepix I am not sure which version you are referring to. The latest version of this module (4.3.0) allows using the correct range of Terraform AWS providers (>=2.42) and the correct version of Terraform (>=0.12.6).

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/versions.tf

**Comment by Porkepix** [comment]
@antonbabenko What I mean by that is that PR #184 introduced this version restriction `aws = ">= 2.42, < 4.0"` and the commit I point to, while only talking about LDAP related change reverted it back to `aws = ">= 2.42"` notation, so I was curious as about why it did so.

This can come from a misunderstanding on my end though, it appears that I though I saw some of our layers still picking the provider v3 due to that, but I guess it might be because of the first apply after module upgrade and that it still used the provider known in the state file.

**Comment by antonbabenko** [comment]
Provider version is not tracked in terraform state, but terraform-aws-provider currently is v3.49.0 that is falling inside the specified range `>= 2.42`. The upper bound of the range (`< 4.0`) is almost never necessary in Terraform AWS modules.

If you want to force an upgrade of the version of the providers you can run `terraform init -upgrade=true`.

**Comment by Porkepix** [comment]
> Provider version is not tracked in terraform state, but terraform-aws-provider currently is v3.49.0 that is falling inside the specified range `>= 2.42`. The upper bound of the range (`< 4.0`) is almost never necessary in Terraform AWS modules.
> 
> If you want to force an upgrade of the version of the providers you can run `terraform init -upgrade=true`.

Yup I always do `terraform init -upgrade`, though I think I got some times where it was still using provider v2. Let's assume it's a mistake on my end and/or due to the different modules such as this one (and a couple of others) I was upgrading. So, sorry for the noise here.

PS: When I was migrating terraform versions, I got situations where it was using both an old and a new provider to satisfy to such constraints, and I believe some of them were coming from the state file. I can obviously be wrong here.

**Pull request merged**
