### PR TITLE
fix: Fixed Splunk rule names

### PR DESCRIPTION
**Pull request by andyshinn**
## Description

The Splunk rule names didn't align which leads to errors like in https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/152

## Motivation and Context

Fixes https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/152.

## Breaking Changes

Should be none.

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by andyshinn** [comment]
Not stale.

**Comment by antonbabenko** [comment]
This PR is included in version 5.1.1 :tada:

**Comment by andyshinn** [comment]
Thanks dawg.

**Comment by antonbabenko** [comment]
Sorry that it took ages :(

**Comment by dhoppe** [comment]
> This PR is included in version 5.1.1 🎉

@antonbabenko Unfortunately this release has not been uploaded to the Terraform registry. 
https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest

**Comment by antonbabenko** [comment]
@dhoppe Fixed.

**Pull request merged**
