### PR TITLE
feat: Add SASL/SCRAM and IAM access control TCP ports for Kafka / MSK

### PR DESCRIPTION
**Pull request by aidanmelen**
Adding rules for all AWS MSK ports: https://docs.aws.amazon.com/msk/latest/developerguide/port-info.html

Completion of @dhoppe's [PR](https://github.com/terraform-aws-modules/terraform-aws-security-group/pull/248)

Closes #248

Fixes https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/244

### CODE REVIEW

**Comment by aidanmelen** [comment]
@antonbabenko Thanks for all your awesome work maintaining these AWS modules. Glad we get to contribute! This PR is now ready for review

**Comment by aidanmelen** [comment]
I ran `pre-commit run -a` and the `update_groups.sh` script.

**Comment by antonbabenko** [comment]
@aidanmelen I don't have permission to push to your fork but I wanted to commit changes after `pre-commit run -a` to make GitHub CI green.

**Comment by aidanmelen** [comment]
@antonbabenko I added you as a collaborator.

**Comment by antonbabenko** [comment]
This PR is included in version 4.13.0 :tada:

**Pull request merged**
