### PR TITLE
fix: Don't use var.(in|e)gress_ipv6_cidr_blocks on security group sourced (in|e)gress

### PR DESCRIPTION
**Pull request by michaelaw320**
# Description
Don't include `var.ingress_ipv6_cidr_blocks` or `var.egress_ipv6_cidr_blocks` for security group sourced ingress / egress rules.

Error such as:
`Error message: the specified rule "peer: ::/0, TCP, from port: 3306, to port: 3306, ALLOW" already exists`
is caused by multiple redefinition of the same IPv6 cidr from the variables mentioned above

Fixes https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/147

Also fix: https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/130 https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/79

### CODE REVIEW

**Comment by michaelaw320** [comment]
@antonbabenko can you take a look at this?
🙇

**Comment by ayk33** [comment]
Can we get some traction on this? This is a big security issue.

**Comment by michaelaw320** [comment]
can we get some traction on this?
I'd like to use this one pretty soon

**Comment by jdaMachado** [comment]
Could we merge this ASAP?

**Comment by michaelaw320** [comment]
Hello @antonbabenko @tcarrondo can we release this?

**Comment by antonbabenko** [comment]
Thanks, @michaelaw320 and all of you who looked into this issue!

[v3.6.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v3.6.0) has been just released.

**Pull request merged**
