### PR TITLE
WIP: Update module for terraform 0.12

### PR DESCRIPTION
**Pull request by alex-goncharov**
This is an attempt to update this module to work with terraform 0.12. Current iteration works with quite simple use cases. 

None of the stuff in ./modules has been tested yet.

### CODE REVIEW

**Comment by vladgh** [comment]
Any update on this?

**Comment by antonbabenko** [comment]
@vladgh I am still working on this today. It is more work than with VPC module which was rather straightforward.

**Comment by vladgh** [comment]
Thank you, your work is appreciated.

**Comment by antonbabenko** [comment]
@alex-goncharov Thanks for this PR! I am looking into it and fixing the rest of this module.

There are few blockers in Terraform 0.12 and other tools which have to be fixed before we can release this module:
- https://github.com/hashicorp/terraform/issues/21403 - panic in `distinct()`
- https://github.com/kvz/json2hcl/issues/12 - find a working replacement in `update_groups.sh`

**Comment by antonbabenko** [comment]
[v3.0.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v3.0.0) has been just released. 🎉

**Pull request closed without merging**
