### PR TITLE
Make creation of the security group optional

### PR DESCRIPTION
**Pull request by robinbowes**
This is an possible way of using this module to manage the rules of an existing Security Group.

One possible use case for this is this situation:

* group 1 - allow access from group 2
* group 2 - allow access from group 1

This causes circular dependencies as the rules of group 1 require the ID of group 2 and vice versa.

By creating the empty groups first and then adding the rules, circular dependencies are avoided.

I've not yet updated the documentation or examples, but I thought I'd push early to get feedback.

Usage would be something like:

```hcl
locals {
  sg_name        = "foo"
  sg_descrpition = "description"
}

resource "aws_security_group" "foo" {
  name        = "${local.sg_name}"
  description = "${local.sg_description}"
}

module "foo_rules" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "2.6.0"

  create_group      = false
  security_group_id = "${aws_security_group.foo.id}"
  name              = "${local.sg_name}"
  description       = "${local.sg_description}"

  # rest of params
}
```

I'd ideally like to not pass in name and description if we're not creating the group but I'm not sure how best to do that.

### CODE REVIEW

**Comment by robinbowes** [comment]
@antonbabenko Any feedback on this? Is it something you'll consider merging once it's tidied up and documenting?

**Comment by antonbabenko** [comment]
@robinbowes It looks pretty good already. Absolutely, I am very much for this PR but very busy with countless other things at the moment.

I should have time to look at this and a few other PRs at the beginning of next week when I am done with traveling for a while.

**Comment by robinbowes** [comment]
Fixed the merge conflict.

**Comment by robinbowes** [comment]
@antonbabenko I'd be interesting in discussing how best to deal with the group name and description when using `create_group = false`.

I'm currently using my fork of the module like this:

```hcl
module "ec2" {
  # temporary module source until my PR gets merged upstream
  source = "github.com/yo61/terraform-aws-security-group?ref=make_create_group_optional"

  create_group      = false
  security_group_id = "${local.sg_this_ec2_id}"
  name              = ""                        # required, but not used
  description       = ""                        # required, but not used
  vpc_id            = "${local.vpc_id}"

  # rules go here
}
```

**Comment by jakauppila** [comment]
We're looking for similar behavior as we hit a cyclical reference problem with 3 security groups that reference each other.

**Comment by samholton** [comment]
Is this PR missing `security_group_id` from `variables.tf`? I'm also not seeing the passed in `security_group_id` being used to add the rules if its not being created.

**Comment by robinbowes** [comment]
> Is this PR missing `security_group_id` from `variables.tf`? I'm also not seeing the passed in `security_group_id` being used to add the rules if its not being created.

Do you mean this?

https://github.com/yo61/terraform-aws-security-group/blob/make_create_group_optional/variables.tf#L14-L17

**Comment by samholton** [comment]
> > Is this PR missing `security_group_id` from `variables.tf`? I'm also not seeing the passed in `security_group_id` being used to add the rules if its not being created.
> 
> Do you mean this?
> 
> https://github.com/yo61/terraform-aws-security-group/blob/make_create_group_optional/variables.tf#L14-L17

I do indeed. No idea what I was looking at, but ignore both of my statements.

**Comment by leo-viridis** [comment]
Any updates on this PR? This feature is really needed.

**Comment by TimJones** [comment]
Such a shame this PR has gone so long without a review. This is pretty essential stuff for security groups.

**Comment by tbugfinder** [comment]
hi @robinbowes 
could you resolve conflicts?

**Comment by robinbowes** [comment]
I'm going to close this in favour of #216 , which is the same change applied to the latest code on master branch.

**Pull request closed without merging**
