### PR TITLE
Add redshift tcp port

### PR DESCRIPTION
**Pull request by ChairmanTubeAmp**

### CODE REVIEW

**Comment by antonbabenko** [comment]
Follow this also - https://github.com/terraform-aws-modules/terraform-aws-security-group#how-to-addupdate-rulesgroups

**Comment by ChairmanTubeAmp** [comment]
I ran that and no files were changed. What am I missing?

**Comment by antonbabenko** [comment]
If you want to create named group, which you should, then make some changes into `auto_groups` variable values and then script will autogenerate correct updates.

**Comment by ChairmanTubeAmp** [comment]
I made the requested change. Anything else needed to accept the PR?

**Comment by antonbabenko** [comment]
[v1.9.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/tag/v1.9.0) is now released.

**Pull request merged**
