### PR TITLE
Evaluate var.create variable to set count to 1 or 0

### PR DESCRIPTION
**Pull request by jordiclariana**
In order to avoid https://github.com/hashicorp/terraform/issues/18195

### CODE REVIEW

**Comment by antonbabenko** [comment]
I don't think this is necessary. Please try to run [examples/disabled](https://github.com/terraform-aws-modules/terraform-aws-security-group/tree/master/examples/disabled) on your local setup.

**Comment by jordiclariana** [comment]
The examples work, and is not the point of the issue in terraform. The problem is when `create` parameter is a result of evaluating a ternary, like this: `create = ${true ? true : false}`. Then it will fail.

**Comment by jordiclariana** [comment]
From the [examples/disabled](https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/examples/disabled/main.tf), notice that I changed the `create` line:

```provider "aws" {
  region = "eu-west-1"
}

#############################################################
# Data sources to get VPC and default security group details
#############################################################
data "aws_vpc" "default" {
  default = true
}

data "aws_security_group" "default" {
  name   = "default"
  vpc_id = "${data.aws_vpc.default.id}"
}

########################################################
# Security groups WILL NOT be created by these examples
########################################################
module "complete_sg_disabled" {
  source = "../../"

  create      = "${true ? false: false}"
  name        = "complete-sg"
  description = "Security group with all available arguments set (this is just an example)"
  vpc_id      = "${data.aws_vpc.default.id}"

  ingress_cidr_blocks = ["0.0.0.0/0"]
}
```

This produces this:
```Error: Error running plan: 2 error(s) occurred:

* module.complete_sg_disabled.aws_security_group.this: cannot parse "false" as an integer
* module.http_sg_disabled.module.sg.aws_security_group.this: cannot parse "false" as an integer
```

**Comment by antonbabenko** [comment]
Jordi, thanks for this PR and for making this module a bit more forward-compatible with the upcoming version of Terraform! :)

**Comment by antonbabenko** [comment]
[v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/tag/v2.1.0) has been released.

**Pull request merged**
